ea4 <-
function(data){
kp <- function(expr) {
    localWarnings <- list()
    value <- withCallingHandlers(expr,
                     warning = function(w) {
                         localWarnings[[length(localWarnings)+1]] <<- w
                         invokeRestart("muffleWarning")
                     })
value=value
} 
res<- list("","","", 
f1<-function(data){ 
names(data)=c("factor_1","factor_2", "factor_3", "response")
data<-data.frame(factor_1=factor(data$factor_1), factor_2=factor(data$factor_2), factor_3=factor(data$factor_3), response=data$response)
m<-aov(response~factor_1*factor_2*factor_3,data=data, contrasts=list(factor_1=contr.sum, factor_2=contr.sum, factor_3=contr.sum))
m1<-aov(response~-1+ factor_1*factor_2*factor_3,data=data, contrasts=list(factor_1=contr.sum, factor_2=contr.sum, factor_3=contr.sum))
m2<-aov(response~-1+ factor_2*factor_1*factor_3,data=data, contrasts=list(factor_1=contr.sum, factor_2=contr.sum, factor_3=contr.sum))
m3<-aov(response~-1+ factor_3*factor_1*factor_2,data=data, contrasts=list(factor_1=contr.sum, factor_2=contr.sum, factor_3=contr.sum))
a2<-Anova(m, type=3) 
a3<-a2[-1,]
residuals<-resid(m)
s<-shapiro.test(residuals)
treatments_f1f2=interaction(data$factor_1,data$factor_2)
treatments_f1f3=interaction(data$factor_1,data$factor_3)
treatments_f2f3=interaction(data$factor_2,data$factor_3)
treatments_f1f2f3=interaction(data$factor_1,data$factor_2, data$factor_3)
treatments_f2f1f3=interaction(data$factor_2,data$factor_1, data$factor_3)
treatments_f3f1f2=interaction(data$factor_3,data$factor_1, data$factor_2)
data<-data.frame(data,treatments_f1f2, treatments_f1f3, treatments_f2f3, treatments_f1f2f3, treatments_f2f1f3, treatments_f3f1f2)
m4<-aov(response~-1+treatments_f1f2+factor_3*treatments_f1f2,data=data, contrasts=list(treatments_f1f2=contr.sum, factor_3=contr.sum))
m5<-aov(response~-1+treatments_f1f3+factor_2*treatments_f1f3,data=data, contrasts=list(treatments_f1f3=contr.sum, factor_2=contr.sum))
m6<-aov(response~-1+treatments_f2f3+factor_1*treatments_f2f3,data=data, contrasts=list(treatments_f2f3=contr.sum, factor_1=contr.sum))
m7<-aov(response~-1+treatments_f1f2f3,data=data, contrasts=list(treatments_f1f2f3=contr.sum))
m8<-aov(response~-1+treatments_f2f1f3,data=data, contrasts=list(treatments_f2f1f3=contr.sum))
m9<-aov(response~-1+treatments_f3f1f2,data=data, contrasts=list(treatments_f3f1f2=contr.sum))
cv<-function(x){sd=(deviance(x)/df.residual(x))^0.5
mm=mean(fitted(x))
r=100*sd/mm
return(round(r,2))}
cvf=cv(m)
Adjust.Means<-coef(m1)[1:nlevels(data$factor_1)]
Standart.Error<-sqrt(diag(vcov(m1)) [1:nlevels(data$factor_1)])
Factor_1<-levels(data$factor_1)
maf1=data.frame(Factor_1,Adjust.Means,Standart.Error)
rownames(maf1)=NULL
Adjust.Means<-coef(m2) [1:nlevels(data$factor_2)]
Standart.Error<-sqrt(diag(vcov(m2))) [1:nlevels(data$factor_2)]
Factor_2<-levels(data$factor_2)
maf2=data.frame(Factor_2,Adjust.Means,Standart.Error)
rownames(maf2)=NULL
Adjust.Means<-coef(m3) [1:nlevels(data$factor_3)]
Standart.Error<-sqrt(diag(vcov(m3))) [1:nlevels(data$factor_3)]
Factor_3<-levels(data$factor_3)
maf3=data.frame(Factor_3,Adjust.Means,Standart.Error)
rownames(maf3)=NULL
Adjust.Means<-coef(m4)[1:nlevels(data$treatments_f1f2)]
Standart.Error<-sqrt(diag(vcov(m4)))[1:nlevels(data$treatments_f1f2)]
Treatments_f1f2<-levels(data$treatments_f1f2)
mat1=data.frame(Treatments_f1f2,Adjust.Means,Standart.Error)
rownames(mat1)=NULL
Adjust.Means<-coef(m5)[1:nlevels(data$treatments_f1f3)]
Standart.Error<-sqrt(diag(vcov(m5)))[1:nlevels(data$treatments_f1f3)]
Treatments_f1f3<-levels(data$treatments_f1f3)
mat2=data.frame(Treatments_f1f3,Adjust.Means,Standart.Error)
rownames(mat2)=NULL
Adjust.Means<-coef(m6)[1:nlevels(data$treatments_f2f3)]
Standart.Error<-sqrt(diag(vcov(m6)))[1:nlevels(data$treatments_f2f3)]
Treatments_f2f3<-levels(data$treatments_f2f3)
mat3=data.frame(Treatments_f2f3,Adjust.Means,Standart.Error)
rownames(mat3)=NULL
Adjust.Means<-coef(m7)[1:nlevels(data$treatments_f1f2f3)]
Standart.Error<-sqrt(diag(vcov(m7)))[1:nlevels(data$treatments_f1f2f3)]
Treatments_f1f2f3<-levels(data$treatments_f1f2f3)
mat4=data.frame(Treatments_f1f2f3,Adjust.Means,Standart.Error)
rownames(mat4)=NULL
test1<-summary(kp(glht (m1,  linfct = mcp(factor_1 = "Tukey"))))
cld(test1)
test2<-summary(kp(glht (m2,  linfct = mcp(factor_2 = "Tukey"))))
cld(test2)
test3<-summary(kp(glht (m3,  linfct = mcp(factor_3 = "Tukey"))))
cld(test3)
test1<-list(test1,cld(test1))
test2<-list(test2,cld(test2))
test3<-list(test3,cld(test3))
test4=kp(glht(m4,  linfct = mcp(treatments_f1f2= "Tukey")))
mc=test4$linfct
x=factor(data$factor_1)
y=factor(data$factor_2)
x=levels(x)
y=levels(y)
x=factor(x)
y=factor(y)
x=reorder(x,c(nlevels(x):1))
y=reorder(y, c(nlevels(y):1))
x1=lapply(levels(x), factor)
y1=lapply(levels(y), factor)
h1=lapply(x1, function(xi){interaction(xi,y)})
h2=lapply(y1, function(yi){interaction(x,yi)})
l1= lapply(h1, levels)
l2= lapply(h2, levels)
aux1<- lapply(l1, function(li){combn(li,2)})
aux2<- lapply(l2, function(li){combn(li,2)})
w1 <- lapply(aux1, function(auxi) {apply(auxi, 2, paste, collapse = " - ")})
w2 <- lapply(aux2, function(auxi) {apply(auxi, 2, paste, collapse = " - ")})
mc=data.frame(mc)
c1=lapply(w1, function(w1i) {        mc[w1i,]    })
c2=lapply(w2, function(w2i) {        mc[w2i,]    })
c1 <- lapply(c1, as.matrix, ncol=length(coef(m4)))
c2 <- lapply(c2, as.matrix, ncol=length(coef(m4)))
r1=lapply(c1, function(c1i) { summary(glht(m4,  linfct =c1i)) })
r2=lapply(c2, function(c2i) { summary(glht(m4,  linfct =c2i)) })
test5= kp(glht (m5,  linfct = mcp(treatments_f1f3= "Tukey")))
mc=test5$linfct
x=factor(data$factor_1)
z=factor(data$factor_3)
x=levels(x)
z=levels(z)
x=factor(x)
z=factor(z)
x=reorder(x,c(nlevels(x):1))
z=reorder(z, c(nlevels(z):1))
x1=lapply(levels(x), factor)
z1=lapply(levels(z), factor)
h1=lapply(x1, function(xi){interaction(xi,z)})
h2=lapply(z1, function(zi){interaction(x,zi)})
l1= lapply(h1, levels)
l2= lapply(h2, levels)
aux1<- lapply(l1, function(li){combn(li,2)})
aux2<- lapply(l2, function(li){combn(li,2)})
w1 <- lapply(aux1, function(auxi) {apply(auxi, 2, paste, collapse = " - ")})
w2 <- lapply(aux2, function(auxi) {apply(auxi, 2, paste, collapse = " - ")})
mc=data.frame(mc)
c1=lapply(w1, function(w1i) {        mc[w1i,]    })
c2=lapply(w2, function(w2i) {        mc[w2i,]    })
c1 <- lapply(c1, as.matrix, ncol=length(coef(m5)))
c2 <- lapply(c2, as.matrix, ncol=length(coef(m5)))
r3=lapply(c1, function(c1i) { summary(glht(m5,  linfct =c1i)) })
r4=lapply(c2, function(c2i) { summary(glht(m5,  linfct =c2i)) })
test6= kp(glht (m6,  linfct = mcp(treatments_f2f3="Tukey")))
mc=test6$linfct
x=factor(data$factor_2)
z=factor(data$factor_3)
x=levels(x)
z=levels(z)
x=factor(x)
z=factor(z)
x=reorder(x,c(nlevels(x):1))
z=reorder(z, c(nlevels(z):1))
x1=lapply(levels(x), factor)
z1=lapply(levels(z), factor)
h1=lapply(x1, function(xi){interaction(xi,z)})
h2=lapply(z1, function(zi){interaction(x,zi)})
l1= lapply(h1, levels)
l2= lapply(h2, levels)
aux1<- lapply(l1, function(li){combn(li,2)})
aux2<- lapply(l2, function(li){combn(li,2)})
w1 <- lapply(aux1, function(auxi) {apply(auxi, 2, paste, collapse = " - ")})
w2 <- lapply(aux2, function(auxi) {apply(auxi, 2, paste, collapse = " - ")})
mc=data.frame(mc)
c1=lapply(w1, function(w1i) {        mc[w1i,]    })
c2=lapply(w2, function(w2i) {        mc[w2i,]    })
c1 <- lapply(c1, as.matrix, ncol=length(coef(m6)))
c2 <- lapply(c2, as.matrix, ncol=length(coef(m6)))
r5=lapply(c1, function(c1i) { summary(glht(m6,  linfct =c1i)) })
r6=lapply(c2, function(c2i) { summary(glht(m6,  linfct =c2i)) })
test7=glht (m7,  linfct = mcp(treatments_f1f2f3= "Tukey" ))
mc=test7$linfct
x=factor(data$factor_1)
y=factor(data$treatments_f2f3)
x=levels(x)
y=levels(y)
x=factor(x)
y=factor(y)
x=reorder(x,c(nlevels(x):1))
y=reorder(y, c(nlevels(y):1))
x1=lapply(levels(x), factor)
y1=lapply(levels(y), factor)
h2=lapply(y1, function(yi){interaction(x,yi)})
l2= lapply(h2, levels)
aux2<- lapply(l2, function(li){combn(li,2)})
w2 <- lapply(aux2, function(auxi) {apply(auxi, 2, paste, collapse = " - ")})
mc=data.frame(mc)
c2=lapply(w2, function(w2i) {        mc[w2i,]    })
c2 <- lapply(c2, as.matrix, ncol=length(coef(m7)))
r7=lapply(c2, function(c2i) { summary(glht(m7,  linfct =c2i)) })
test8=glht (m8,  linfct = mcp(treatments_f2f1f3= "Tukey" ))
mc=test8$linfct
x=factor(data$factor_2)
y=factor(data$treatments_f1f3)
x=levels(x)
y=levels(y)
x=factor(x)
y=factor(y)
x=reorder(x,c(nlevels(x):1))
y=reorder(y, c(nlevels(y):1))
x1=lapply(levels(x), factor)
y1=lapply(levels(y), factor)
h2=lapply(y1, function(yi){interaction(x,yi)})
l2= lapply(h2, levels)
aux2<- lapply(l2, function(li){combn(li,2)})
w2 <- lapply(aux2, function(auxi) {apply(auxi, 2, paste, collapse = " - ")})
mc=data.frame(mc)
c2=lapply(w2, function(w2i) {        mc[w2i,]    })
c2 <- lapply(c2, as.matrix, ncol=length(coef(m8)))
r8=lapply(c2, function(c2i) { summary(glht(m8,  linfct =c2i)) })
test9=glht (m9,  linfct = mcp(treatments_f3f1f2= "Tukey" ))
mc=test9$linfct
x=factor(data$factor_3)
y=factor(data$treatments_f1f2)
x=levels(x)
y=levels(y)
x=factor(x)
y=factor(y)
x=reorder(x,c(nlevels(x):1))
y=reorder(y, c(nlevels(y):1))
x1=lapply(levels(x), factor)
y1=lapply(levels(y), factor)
h2=lapply(y1, function(yi){interaction(x,yi)})
l2= lapply(h2, levels)
aux2<- lapply(l2, function(li){combn(li,2)})
w2 <- lapply(aux2, function(auxi) {apply(auxi, 2, paste, collapse = " - ")})
mc=data.frame(mc)
c2=lapply(w2, function(w2i) {        mc[w2i,]    })
c2 <- lapply(c2, as.matrix, ncol=length(coef(m9)))
r9=lapply(c2, function(c2i) { summary(glht(m9,  linfct =c2i)) })
l<-list(a3,s,cvf, maf1, maf2, maf3, mat1, mat2, mat3, mat4, test1,test2, test3, r2, r1, r4,r3,r6,r5,r7,r8,r9)
names(l)= list("Analysis of variance", "Normality test ", "Coefficient of variation (%)","Adjusted means (factor 1)", "Adjusted means (factor 2)", "Adjusted means (factor 3)", "Adjusted means (treatments_f1f2)", "Adjusted means (treatments_f1f3)", "Adjusted means (treatments_f2f3)", "Adjusted means (treatments_f1f2f3)","Multiple comparison test (factor 1)", "Multiple comparison test (factor 2)", "Multiple comparison test (factor 3)","Multiple comparison test (factor 1 in levels of factor 2)", "Multiple comparison test (factor 2 in levels of factor 1)","Multiple comparison test (factor 1 in levels of factor 3)", "Multiple comparison test (factor 3 in levels of factor 1)", "Multiple comparison test (factor 2 in levels of factor 3)","Multiple comparison test (factor 3 in levels of factor 2)","Multiple comparison test (factor 1 in levels of treatments factor 2 * factor 3)","Multiple comparison test (factor 2 in levels of treatments factor 1 * factor 3)", "Multiple comparison test (factor 3 in levels of treatments factor 1 * factor 2)")
return(l)
}
,
f2<-function(data){ 
names(data)=c("factor_1","factor_2", "factor_3", "blocks","response")
data<-data.frame(factor_1=factor(data$factor_1), factor_2=factor(data$factor_2), factor_3=factor(data$factor_3), blocks=factor(data$blocks), response=data$response)
m<-aov(response~factor_1*factor_2*factor_3+ blocks,data=data, contrasts=list(factor_1=contr.sum, factor_2=contr.sum, factor_3=contr.sum, blocks=contr.sum))
m1<-aov(response~-1+ factor_1*factor_2*factor_3+ blocks,data=data, contrasts=list(factor_1=contr.sum, factor_2=contr.sum, factor_3=contr.sum, blocks=contr.sum))
m2<-aov(response~-1+ factor_2*factor_1*factor_3+ blocks,data=data, contrasts=list(factor_1=contr.sum, factor_2=contr.sum, factor_3=contr.sum, blocks=contr.sum))
m3<-aov(response~-1+ factor_3*factor_1*factor_2+ blocks,data=data, contrasts=list(factor_1=contr.sum, factor_2=contr.sum, factor_3=contr.sum, blocks=contr.sum))
a2<-Anova(m, type=3) 
a3<-a2[-1,]
residuals<-resid(m)
s<-shapiro.test(residuals)
treatments_f1f2=interaction(data$factor_1,data$factor_2)
treatments_f1f3=interaction(data$factor_1,data$factor_3)
treatments_f2f3=interaction(data$factor_2,data$factor_3)
treatments_f1f2f3=interaction(data$factor_1,data$factor_2, data$factor_3)
treatments_f2f1f3=interaction(data$factor_2,data$factor_1, data$factor_3)
treatments_f3f1f2=interaction(data$factor_3,data$factor_1, data$factor_2)
data<-data.frame(data,treatments_f1f2, treatments_f1f3, treatments_f2f3, treatments_f1f2f3, treatments_f2f1f3, treatments_f3f1f2)
m4<-aov(response~-1+treatments_f1f2+factor_3*treatments_f1f2+ blocks,data=data, contrasts=list(treatments_f1f2=contr.sum, factor_3=contr.sum, blocks=contr.sum))
m5<-aov(response~-1+treatments_f1f3+factor_2*treatments_f1f3+ blocks,data=data, contrasts=list(treatments_f1f3=contr.sum, factor_2=contr.sum, blocks=contr.sum))
m6<-aov(response~-1+treatments_f2f3+factor_1*treatments_f2f3+blocks,data=data, contrasts=list(treatments_f2f3=contr.sum, factor_1=contr.sum, blocks=contr.sum))
m7<-aov(response~-1+treatments_f1f2f3+ blocks,data=data, contrasts=list(treatments_f1f2f3=contr.sum, blocks=contr.sum))
m8<-aov(response~-1+treatments_f2f1f3+ blocks,data=data, contrasts=list(treatments_f2f1f3=contr.sum, blocks=contr.sum))
m9<-aov(response~-1+treatments_f3f1f2+ blocks,data=data, contrasts=list(treatments_f3f1f2=contr.sum, blocks=contr.sum))
cv<-function(x){sd=(deviance(x)/df.residual(x))^0.5
mm=mean(fitted(x))
r=100*sd/mm
return(round(r,2))}
cvf=cv(m)
Adjust.Means<-coef(m1)[1:nlevels(data$factor_1)]
Standart.Error<-sqrt(diag(vcov(m1)) [1:nlevels(data$factor_1)])
Factor_1<-levels(data$factor_1)
maf1=data.frame(Factor_1,Adjust.Means,Standart.Error)
rownames(maf1)=NULL
Adjust.Means<-coef(m2) [1:nlevels(data$factor_2)]
Standart.Error<-sqrt(diag(vcov(m2))) [1:nlevels(data$factor_2)]
Factor_2<-levels(data$factor_2)
maf2=data.frame(Factor_2,Adjust.Means,Standart.Error)
rownames(maf2)=NULL
Adjust.Means<-coef(m3) [1:nlevels(data$factor_3)]
Standart.Error<-sqrt(diag(vcov(m3))) [1:nlevels(data$factor_3)]
Factor_3<-levels(data$factor_3)
maf3=data.frame(Factor_3,Adjust.Means,Standart.Error)
rownames(maf3)=NULL
Adjust.Means<-coef(m4)[1:nlevels(data$treatments_f1f2)]
Standart.Error<-sqrt(diag(vcov(m4)))[1:nlevels(data$treatments_f1f2)]
Treatments_f1f2<-levels(data$treatments_f1f2)
mat1=data.frame(Treatments_f1f2,Adjust.Means,Standart.Error)
rownames(mat1)=NULL
Adjust.Means<-coef(m5)[1:nlevels(data$treatments_f1f3)]
Standart.Error<-sqrt(diag(vcov(m5)))[1:nlevels(data$treatments_f1f3)]
Treatments_f1f3<-levels(data$treatments_f1f3)
mat2=data.frame(Treatments_f1f3,Adjust.Means,Standart.Error)
rownames(mat2)=NULL
Adjust.Means<-coef(m6)[1:nlevels(data$treatments_f2f3)]
Standart.Error<-sqrt(diag(vcov(m6)))[1:nlevels(data$treatments_f2f3)]
Treatments_f2f3<-levels(data$treatments_f2f3)
mat3=data.frame(Treatments_f2f3,Adjust.Means,Standart.Error)
rownames(mat3)=NULL
Adjust.Means<-coef(m7)[1:nlevels(data$treatments_f1f2f3)]
Standart.Error<-sqrt(diag(vcov(m7)))[1:nlevels(data$treatments_f1f2f3)]
Treatments_f1f2f3<-levels(data$treatments_f1f2f3)
mat4=data.frame(Treatments_f1f2f3,Adjust.Means,Standart.Error)
rownames(mat4)=NULL
test1<-summary(kp(glht (m1,  linfct = mcp(factor_1 = "Tukey"))))
cld(test1)
test2<-summary(kp(glht (m2,  linfct = mcp(factor_2 = "Tukey"))))
cld(test2)
test3<-summary(kp(glht (m3,  linfct = mcp(factor_3 = "Tukey"))))
cld(test3)
test1<-list(test1,cld(test1))
test2<-list(test2,cld(test2))
test3<-list(test3,cld(test3))
test4=kp(glht(m4,  linfct = mcp(treatments_f1f2= "Tukey")))
mc=test4$linfct
x=factor(data$factor_1)
y=factor(data$factor_2)
x=levels(x)
y=levels(y)
x=factor(x)
y=factor(y)
x=reorder(x,c(nlevels(x):1))
y=reorder(y, c(nlevels(y):1))
x1=lapply(levels(x), factor)
y1=lapply(levels(y), factor)
h1=lapply(x1, function(xi){interaction(xi,y)})
h2=lapply(y1, function(yi){interaction(x,yi)})
l1= lapply(h1, levels)
l2= lapply(h2, levels)
aux1<- lapply(l1, function(li){combn(li,2)})
aux2<- lapply(l2, function(li){combn(li,2)})
w1 <- lapply(aux1, function(auxi) {apply(auxi, 2, paste, collapse = " - ")})
w2 <- lapply(aux2, function(auxi) {apply(auxi, 2, paste, collapse = " - ")})
mc=data.frame(mc)
c1=lapply(w1, function(w1i) {        mc[w1i,]    })
c2=lapply(w2, function(w2i) {        mc[w2i,]    })
c1 <- lapply(c1, as.matrix, ncol=length(coef(m4)))
c2 <- lapply(c2, as.matrix, ncol=length(coef(m4)))
r1=lapply(c1, function(c1i) { summary(glht(m4,  linfct =c1i)) })
r2=lapply(c2, function(c2i) { summary(glht(m4,  linfct =c2i)) })
test5= kp(glht (m5,  linfct = mcp(treatments_f1f3= "Tukey")))
mc=test5$linfct
x=factor(data$factor_1)
z=factor(data$factor_3)
x=levels(x)
z=levels(z)
x=factor(x)
z=factor(z)
x=reorder(x,c(nlevels(x):1))
z=reorder(z, c(nlevels(z):1))
x1=lapply(levels(x), factor)
z1=lapply(levels(z), factor)
h1=lapply(x1, function(xi){interaction(xi,z)})
h2=lapply(z1, function(zi){interaction(x,zi)})
l1= lapply(h1, levels)
l2= lapply(h2, levels)
aux1<- lapply(l1, function(li){combn(li,2)})
aux2<- lapply(l2, function(li){combn(li,2)})
w1 <- lapply(aux1, function(auxi) {apply(auxi, 2, paste, collapse = " - ")})
w2 <- lapply(aux2, function(auxi) {apply(auxi, 2, paste, collapse = " - ")})
mc=data.frame(mc)
c1=lapply(w1, function(w1i) {        mc[w1i,]    })
c2=lapply(w2, function(w2i) {        mc[w2i,]    })
c1 <- lapply(c1, as.matrix, ncol=length(coef(m5)))
c2 <- lapply(c2, as.matrix, ncol=length(coef(m5)))
r3=lapply(c1, function(c1i) { summary(glht(m5,  linfct =c1i)) })
r4=lapply(c2, function(c2i) { summary(glht(m5,  linfct =c2i)) })
test6= kp(glht (m6,  linfct = mcp(treatments_f2f3="Tukey")))
mc=test6$linfct
x=factor(data$factor_2)
z=factor(data$factor_3)
x=levels(x)
z=levels(z)
x=factor(x)
z=factor(z)
x=reorder(x,c(nlevels(x):1))
z=reorder(z, c(nlevels(z):1))
x1=lapply(levels(x), factor)
z1=lapply(levels(z), factor)
h1=lapply(x1, function(xi){interaction(xi,z)})
h2=lapply(z1, function(zi){interaction(x,zi)})
l1= lapply(h1, levels)
l2= lapply(h2, levels)
aux1<- lapply(l1, function(li){combn(li,2)})
aux2<- lapply(l2, function(li){combn(li,2)})
w1 <- lapply(aux1, function(auxi) {apply(auxi, 2, paste, collapse = " - ")})
w2 <- lapply(aux2, function(auxi) {apply(auxi, 2, paste, collapse = " - ")})
mc=data.frame(mc)
c1=lapply(w1, function(w1i) {        mc[w1i,]    })
c2=lapply(w2, function(w2i) {        mc[w2i,]    })
c1 <- lapply(c1, as.matrix, ncol=length(coef(m6)))
c2 <- lapply(c2, as.matrix, ncol=length(coef(m6)))
r5=lapply(c1, function(c1i) { summary(glht(m6,  linfct =c1i)) })
r6=lapply(c2, function(c2i) { summary(glht(m6,  linfct =c2i)) })
test7=glht (m7,  linfct = mcp(treatments_f1f2f3= "Tukey" ))
mc=test7$linfct
x=factor(data$factor_1)
y=factor(data$treatments_f2f3)
x=levels(x)
y=levels(y)
x=factor(x)
y=factor(y)
x=reorder(x,c(nlevels(x):1))
y=reorder(y, c(nlevels(y):1))
x1=lapply(levels(x), factor)
y1=lapply(levels(y), factor)
h2=lapply(y1, function(yi){interaction(x,yi)})
l2= lapply(h2, levels)
aux2<- lapply(l2, function(li){combn(li,2)})
w2 <- lapply(aux2, function(auxi) {apply(auxi, 2, paste, collapse = " - ")})
mc=data.frame(mc)
c2=lapply(w2, function(w2i) {        mc[w2i,]    })
c2 <- lapply(c2, as.matrix, ncol=length(coef(m7)))
r7=lapply(c2, function(c2i) { summary(glht(m7,  linfct =c2i)) })
test8=glht (m8,  linfct = mcp(treatments_f2f1f3= "Tukey" ))
mc=test8$linfct
x=factor(data$factor_2)
y=factor(data$treatments_f1f3)
x=levels(x)
y=levels(y)
x=factor(x)
y=factor(y)
x=reorder(x,c(nlevels(x):1))
y=reorder(y, c(nlevels(y):1))
x1=lapply(levels(x), factor)
y1=lapply(levels(y), factor)
h2=lapply(y1, function(yi){interaction(x,yi)})
l2= lapply(h2, levels)
aux2<- lapply(l2, function(li){combn(li,2)})
w2 <- lapply(aux2, function(auxi) {apply(auxi, 2, paste, collapse = " - ")})
mc=data.frame(mc)
c2=lapply(w2, function(w2i) {        mc[w2i,]    })
c2 <- lapply(c2, as.matrix, ncol=length(coef(m8)))
r8=lapply(c2, function(c2i) { summary(glht(m8,  linfct =c2i)) })
test9=glht (m9,  linfct = mcp(treatments_f3f1f2= "Tukey" ))
mc=test9$linfct
x=factor(data$factor_3)
y=factor(data$treatments_f1f2)
x=levels(x)
y=levels(y)
x=factor(x)
y=factor(y)
x=reorder(x,c(nlevels(x):1))
y=reorder(y, c(nlevels(y):1))
x1=lapply(levels(x), factor)
y1=lapply(levels(y), factor)
h2=lapply(y1, function(yi){interaction(x,yi)})
l2= lapply(h2, levels)
aux2<- lapply(l2, function(li){combn(li,2)})
w2 <- lapply(aux2, function(auxi) {apply(auxi, 2, paste, collapse = " - ")})
mc=data.frame(mc)
c2=lapply(w2, function(w2i) {        mc[w2i,]    })
c2 <- lapply(c2, as.matrix, ncol=length(coef(m9)))
r9=lapply(c2, function(c2i) { summary(glht(m9,  linfct =c2i)) })
l<-list(a3,s,cvf, maf1, maf2, maf3, mat1, mat2, mat3, mat4, test1,test2, test3, r2, r1, r4,r3,r6,r5,r7,r8,r9)
names(l)= list("Analysis of variance", "Normality test ", "Coefficient of variation (%)","Adjusted means (factor 1)", "Adjusted means (factor 2)", "Adjusted means (factor 3)", "Adjusted means (treatments_f1f2)", "Adjusted means (treatments_f1f3)", "Adjusted means (treatments_f2f3)", "Adjusted means (treatments_f1f2f3)","Multiple comparison test (factor 1)", "Multiple comparison test (factor 2)", "Multiple comparison test (factor 3)","Multiple comparison test (factor 1 in levels of factor 2)", "Multiple comparison test (factor 2 in levels of factor 1)","Multiple comparison test (factor 1 in levels of factor 3)", "Multiple comparison test (factor 3 in levels of factor 1)", "Multiple comparison test (factor 2 in levels of factor 3)","Multiple comparison test (factor 3 in levels of factor 2)","Multiple comparison test (factor 1 in levels of treatments factor 2 * factor 3)","Multiple comparison test (factor 2 in levels of treatments factor 1 * factor 3)", "Multiple comparison test (factor 3 in levels of treatments factor 1 * factor 2)")
return(l)
}
,
f3<-function(data){ 
names(data)=c("factor_1","factor_2", "factor_3","rows","cols", "response")
data<-data.frame(factor_1=factor(data$factor_1), factor_2=factor(data$factor_2), factor_3=factor(data$factor_3),  rows=factor(data$rows), cols=factor(data$cols), response=data$response)
m<-aov(response~factor_1*factor_2*factor_3+rows+cols,data=data, contrasts=list(factor_1=contr.sum, factor_2=contr.sum, factor_3=contr.sum ,rows=contr.sum, cols=contr.sum))
m1<-aov(response~-1+ factor_1*factor_2*factor_3+rows+cols,data=data, contrasts=list(factor_1=contr.sum, factor_2=contr.sum, factor_3=contr.sum,rows=contr.sum, cols=contr.sum))
m2<-aov(response~-1+ factor_2*factor_1*factor_3+rows+cols,data=data, contrasts=list(factor_1=contr.sum, factor_2=contr.sum, factor_3=contr.sum,rows=contr.sum, cols=contr.sum))
m3<-aov(response~-1+ factor_3*factor_1*factor_2+rows+cols,data=data, contrasts=list(factor_1=contr.sum, factor_2=contr.sum, factor_3=contr.sum,rows=contr.sum, cols=contr.sum))
a2<-Anova(m, type=3) 
a3<-a2[-1,]
residuals<-resid(m)
s<-shapiro.test(residuals)
treatments_f1f2=interaction(data$factor_1,data$factor_2)
treatments_f1f3=interaction(data$factor_1,data$factor_3)
treatments_f2f3=interaction(data$factor_2,data$factor_3)
treatments_f1f2f3=interaction(data$factor_1,data$factor_2, data$factor_3)
treatments_f2f1f3=interaction(data$factor_2,data$factor_1, data$factor_3)
treatments_f3f1f2=interaction(data$factor_3,data$factor_1, data$factor_2)
data<-data.frame(data,treatments_f1f2, treatments_f1f3, treatments_f2f3, treatments_f1f2f3, treatments_f2f1f3, treatments_f3f1f2)
m4<-aov(response~-1+treatments_f1f2+factor_3*treatments_f1f2+rows+cols,data=data, contrasts=list(treatments_f1f2=contr.sum, factor_3=contr.sum,rows=contr.sum, cols=contr.sum))
m5<-aov(response~-1+treatments_f1f3+factor_2*treatments_f1f3+rows+cols,data=data, contrasts=list(treatments_f1f3=contr.sum, factor_2=contr.sum,rows=contr.sum, cols=contr.sum))
m6<-aov(response~-1+treatments_f2f3+factor_1*treatments_f2f3+rows+cols,data=data, contrasts=list(treatments_f2f3=contr.sum, factor_1=contr.sum,rows=contr.sum, cols=contr.sum))
m7<-aov(response~-1+treatments_f1f2f3+rows+cols,data=data, contrasts=list(treatments_f1f2f3=contr.sum,rows=contr.sum, cols=contr.sum))
m8<-aov(response~-1+treatments_f2f1f3+rows+cols,data=data, contrasts=list(treatments_f2f1f3=contr.sum,rows=contr.sum, cols=contr.sum))
m9<-aov(response~-1+treatments_f3f1f2+rows+cols,data=data, contrasts=list(treatments_f3f1f2=contr.sum,rows=contr.sum, cols=contr.sum))
cv<-function(x){sd=(deviance(x)/df.residual(x))^0.5
mm=mean(fitted(x))
r=100*sd/mm
return(round(r,2))}
cvf=cv(m)
Adjust.Means<-coef(m1)[1:nlevels(data$factor_1)]
Standart.Error<-sqrt(diag(vcov(m1)) [1:nlevels(data$factor_1)])
Factor_1<-levels(data$factor_1)
maf1=data.frame(Factor_1,Adjust.Means,Standart.Error)
rownames(maf1)=NULL
Adjust.Means<-coef(m2) [1:nlevels(data$factor_2)]
Standart.Error<-sqrt(diag(vcov(m2))) [1:nlevels(data$factor_2)]
Factor_2<-levels(data$factor_2)
maf2=data.frame(Factor_2,Adjust.Means,Standart.Error)
rownames(maf2)=NULL
Adjust.Means<-coef(m3) [1:nlevels(data$factor_3)]
Standart.Error<-sqrt(diag(vcov(m3))) [1:nlevels(data$factor_3)]
Factor_3<-levels(data$factor_3)
maf3=data.frame(Factor_3,Adjust.Means,Standart.Error)
rownames(maf3)=NULL
Adjust.Means<-coef(m4)[1:nlevels(data$treatments_f1f2)]
Standart.Error<-sqrt(diag(vcov(m4)))[1:nlevels(data$treatments_f1f2)]
Treatments_f1f2<-levels(data$treatments_f1f2)
mat1=data.frame(Treatments_f1f2,Adjust.Means,Standart.Error)
rownames(mat1)=NULL
Adjust.Means<-coef(m5)[1:nlevels(data$treatments_f1f3)]
Standart.Error<-sqrt(diag(vcov(m5)))[1:nlevels(data$treatments_f1f3)]
Treatments_f1f3<-levels(data$treatments_f1f3)
mat2=data.frame(Treatments_f1f3,Adjust.Means,Standart.Error)
rownames(mat2)=NULL
Adjust.Means<-coef(m6)[1:nlevels(data$treatments_f2f3)]
Standart.Error<-sqrt(diag(vcov(m6)))[1:nlevels(data$treatments_f2f3)]
Treatments_f2f3<-levels(data$treatments_f2f3)
mat3=data.frame(Treatments_f2f3,Adjust.Means,Standart.Error)
rownames(mat3)=NULL
Adjust.Means<-coef(m7)[1:nlevels(data$treatments_f1f2f3)]
Standart.Error<-sqrt(diag(vcov(m7)))[1:nlevels(data$treatments_f1f2f3)]
Treatments_f1f2f3<-levels(data$treatments_f1f2f3)
mat4=data.frame(Treatments_f1f2f3,Adjust.Means,Standart.Error)
rownames(mat4)=NULL
test1<-summary(kp(glht (m1,  linfct = mcp(factor_1 = "Tukey"))))
cld(test1)
test2<-summary(kp(glht (m2,  linfct = mcp(factor_2 = "Tukey"))))
cld(test2)
test3<-summary(kp(glht (m3,  linfct = mcp(factor_3 = "Tukey"))))
cld(test3)
test1<-list(test1,cld(test1))
test2<-list(test2,cld(test2))
test3<-list(test3,cld(test3))
test4=kp(glht(m4,  linfct = mcp(treatments_f1f2= "Tukey")))
mc=test4$linfct
x=factor(data$factor_1)
y=factor(data$factor_2)
x=levels(x)
y=levels(y)
x=factor(x)
y=factor(y)
x=reorder(x,c(nlevels(x):1))
y=reorder(y, c(nlevels(y):1))
x1=lapply(levels(x), factor)
y1=lapply(levels(y), factor)
h1=lapply(x1, function(xi){interaction(xi,y)})
h2=lapply(y1, function(yi){interaction(x,yi)})
l1= lapply(h1, levels)
l2= lapply(h2, levels)
aux1<- lapply(l1, function(li){combn(li,2)})
aux2<- lapply(l2, function(li){combn(li,2)})
w1 <- lapply(aux1, function(auxi) {apply(auxi, 2, paste, collapse = " - ")})
w2 <- lapply(aux2, function(auxi) {apply(auxi, 2, paste, collapse = " - ")})
mc=data.frame(mc)
c1=lapply(w1, function(w1i) {        mc[w1i,]    })
c2=lapply(w2, function(w2i) {        mc[w2i,]    })
c1 <- lapply(c1, as.matrix, ncol=length(coef(m4)))
c2 <- lapply(c2, as.matrix, ncol=length(coef(m4)))
r1=lapply(c1, function(c1i) { summary(glht(m4,  linfct =c1i)) })
r2=lapply(c2, function(c2i) { summary(glht(m4,  linfct =c2i)) })
test5= kp(glht (m5,  linfct = mcp(treatments_f1f3= "Tukey")))
mc=test5$linfct
x=factor(data$factor_1)
z=factor(data$factor_3)
x=levels(x)
z=levels(z)
x=factor(x)
z=factor(z)
x=reorder(x,c(nlevels(x):1))
z=reorder(z, c(nlevels(z):1))
x1=lapply(levels(x), factor)
z1=lapply(levels(z), factor)
h1=lapply(x1, function(xi){interaction(xi,z)})
h2=lapply(z1, function(zi){interaction(x,zi)})
l1= lapply(h1, levels)
l2= lapply(h2, levels)
aux1<- lapply(l1, function(li){combn(li,2)})
aux2<- lapply(l2, function(li){combn(li,2)})
w1 <- lapply(aux1, function(auxi) {apply(auxi, 2, paste, collapse = " - ")})
w2 <- lapply(aux2, function(auxi) {apply(auxi, 2, paste, collapse = " - ")})
mc=data.frame(mc)
c1=lapply(w1, function(w1i) {        mc[w1i,]    })
c2=lapply(w2, function(w2i) {        mc[w2i,]    })
c1 <- lapply(c1, as.matrix, ncol=length(coef(m5)))
c2 <- lapply(c2, as.matrix, ncol=length(coef(m5)))
r3=lapply(c1, function(c1i) { summary(glht(m5,  linfct =c1i)) })
r4=lapply(c2, function(c2i) { summary(glht(m5,  linfct =c2i)) })
test6= kp(glht (m6,  linfct = mcp(treatments_f2f3="Tukey")))
mc=test6$linfct
x=factor(data$factor_2)
z=factor(data$factor_3)
x=levels(x)
z=levels(z)
x=factor(x)
z=factor(z)
x=reorder(x,c(nlevels(x):1))
z=reorder(z, c(nlevels(z):1))
x1=lapply(levels(x), factor)
z1=lapply(levels(z), factor)
h1=lapply(x1, function(xi){interaction(xi,z)})
h2=lapply(z1, function(zi){interaction(x,zi)})
l1= lapply(h1, levels)
l2= lapply(h2, levels)
aux1<- lapply(l1, function(li){combn(li,2)})
aux2<- lapply(l2, function(li){combn(li,2)})
w1 <- lapply(aux1, function(auxi) {apply(auxi, 2, paste, collapse = " - ")})
w2 <- lapply(aux2, function(auxi) {apply(auxi, 2, paste, collapse = " - ")})
mc=data.frame(mc)
c1=lapply(w1, function(w1i) {        mc[w1i,]    })
c2=lapply(w2, function(w2i) {        mc[w2i,]    })
c1 <- lapply(c1, as.matrix, ncol=length(coef(m6)))
c2 <- lapply(c2, as.matrix, ncol=length(coef(m6)))
r5=lapply(c1, function(c1i) { summary(glht(m6,  linfct =c1i)) })
r6=lapply(c2, function(c2i) { summary(glht(m6,  linfct =c2i)) })
test7=glht (m7,  linfct = mcp(treatments_f1f2f3= "Tukey" ))
mc=test7$linfct
x=factor(data$factor_1)
y=factor(data$treatments_f2f3)
x=levels(x)
y=levels(y)
x=factor(x)
y=factor(y)
x=reorder(x,c(nlevels(x):1))
y=reorder(y, c(nlevels(y):1))
x1=lapply(levels(x), factor)
y1=lapply(levels(y), factor)
h2=lapply(y1, function(yi){interaction(x,yi)})
l2= lapply(h2, levels)
aux2<- lapply(l2, function(li){combn(li,2)})
w2 <- lapply(aux2, function(auxi) {apply(auxi, 2, paste, collapse = " - ")})
mc=data.frame(mc)
c2=lapply(w2, function(w2i) {        mc[w2i,]    })
c2 <- lapply(c2, as.matrix, ncol=length(coef(m7)))
r7=lapply(c2, function(c2i) { summary(glht(m7,  linfct =c2i)) })
test8=glht (m8,  linfct = mcp(treatments_f2f1f3= "Tukey" ))
mc=test8$linfct
x=factor(data$factor_2)
y=factor(data$treatments_f1f3)
x=levels(x)
y=levels(y)
x=factor(x)
y=factor(y)
x=reorder(x,c(nlevels(x):1))
y=reorder(y, c(nlevels(y):1))
x1=lapply(levels(x), factor)
y1=lapply(levels(y), factor)
h2=lapply(y1, function(yi){interaction(x,yi)})
l2= lapply(h2, levels)
aux2<- lapply(l2, function(li){combn(li,2)})
w2 <- lapply(aux2, function(auxi) {apply(auxi, 2, paste, collapse = " - ")})
mc=data.frame(mc)
c2=lapply(w2, function(w2i) {        mc[w2i,]    })
c2 <- lapply(c2, as.matrix, ncol=length(coef(m8)))
r8=lapply(c2, function(c2i) {summary(glht(m8,  linfct =c2i)) })
test9=glht (m9,  linfct = mcp(treatments_f3f1f2= "Tukey" ))
mc=test9$linfct
x=factor(data$factor_3)
y=factor(data$treatments_f1f2)
x=levels(x)
y=levels(y)
x=factor(x)
y=factor(y)
x=reorder(x,c(nlevels(x):1))
y=reorder(y, c(nlevels(y):1))
x1=lapply(levels(x), factor)
y1=lapply(levels(y), factor)
h2=lapply(y1, function(yi){interaction(x,yi)})
l2= lapply(h2, levels)
aux2<- lapply(l2, function(li){combn(li,2)})
w2 <- lapply(aux2, function(auxi) {apply(auxi, 2, paste, collapse = " - ")})
mc=data.frame(mc)
c2=lapply(w2, function(w2i) {        mc[w2i,]    })
c2 <- lapply(c2, as.matrix, ncol=length(coef(m9)))
r9=lapply(c2, function(c2i) { summary(glht(m9,  linfct =c2i)) })
l<-list(a3,s,cvf, maf1, maf2, maf3, mat1, mat2, mat3, mat4, test1,test2, test3, r2, r1, r4,r3,r6,r5,r7,r8,r9)
names(l)= list("Analysis of variance", "Normality test ", "Coefficient of variation (%)","Adjusted means (factor 1)", "Adjusted means (factor 2)", "Adjusted means (factor 3)", "Adjusted means (treatments_f1f2)", "Adjusted means (treatments_f1f3)", "Adjusted means (treatments_f2f3)", "Adjusted means (treatments_f1f2f3)","Multiple comparison test (factor 1)", "Multiple comparison test (factor 2)", "Multiple comparison test (factor 3)","Multiple comparison test (factor 1 in levels of factor 2)", "Multiple comparison test (factor 2 in levels of factor 1)","Multiple comparison test (factor 1 in levels of factor 3)", "Multiple comparison test (factor 3 in levels of factor 1)", "Multiple comparison test (factor 2 in levels of factor 3)","Multiple comparison test (factor 3 in levels of factor 2)","Multiple comparison test (factor 1 in levels of treatments factor 2 * factor 3)","Multiple comparison test (factor 2 in levels of treatments factor 1 * factor 3)", "Multiple comparison test (factor 3 in levels of treatments factor 1 * factor 2)")
return(l)
}
)
g=res[[length(data)]]
g(data)
}
